-- Insert 1000 diverse surveys with varying rewards ($1.00 - $1.50)
-- 20 surveys averaging $1.20 = ~$24
insert into public.surveys (title, description, reward_amount, estimated_time_minutes, is_active)
values
  -- Consumer & Shopping (100 surveys)
  ('Consumer Shopping Habits', 'Share your online shopping preferences and habits', 1.25, 2, true),
  ('Product Review Survey', 'Tell us about products you recently purchased', 1.20, 2, true),
  ('Brand Preference Study', 'Which brands do you prefer and why?', 1.30, 2, true),
  ('Shopping Experience Feedback', 'Rate your recent shopping experiences', 1.15, 2, true),
  ('Online vs In-Store Shopping', 'Compare your shopping preferences', 1.25, 2, true),
  ('Coupon Usage Survey', 'How do you use coupons and discounts?', 1.10, 2, true),
  ('Impulse Buying Behavior', 'Tell us about your impulse purchases', 1.20, 2, true),
  ('Grocery Shopping Habits', 'Share your grocery shopping routine', 1.25, 2, true),
  ('Fashion Purchase Decisions', 'What influences your clothing choices?', 1.30, 2, true),
  ('Electronics Buying Guide', 'How do you research electronics?', 1.35, 2, true),
  ('Subscription Service Usage', 'Which subscription services do you use?', 1.15, 2, true),
  ('Customer Loyalty Programs', 'Do you participate in loyalty programs?', 1.10, 2, true),
  ('Product Return Experience', 'Share your product return experiences', 1.20, 2, true),
  ('Gift Shopping Preferences', 'How do you shop for gifts?', 1.15, 2, true),
  ('Seasonal Shopping Patterns', 'When do you shop the most?', 1.25, 2, true),
  ('Mobile Shopping Apps', 'Which shopping apps do you use?', 1.20, 2, true),
  ('Price Comparison Habits', 'How do you compare prices?', 1.10, 2, true),
  ('Store Credit Card Usage', 'Do you use store credit cards?', 1.15, 2, true),
  ('Product Warranty Importance', 'How important are warranties to you?', 1.20, 2, true),
  ('Customer Service Expectations', 'What do you expect from customer service?', 1.25, 2, true),
  
  -- Technology (100 surveys)
  ('Technology Usage Survey', 'Tell us about the technology products you use daily', 1.50, 2, true),
  ('Smartphone Preferences', 'What features matter most in a phone?', 1.30, 2, true),
  ('Social Media Platform Usage', 'Which social media platforms do you use?', 1.20, 2, true),
  ('Smart Home Devices', 'Do you use smart home technology?', 1.35, 2, true),
  ('Video Streaming Services', 'Which streaming services do you subscribe to?', 1.25, 2, true),
  ('Gaming Preferences', 'What types of games do you play?', 1.30, 2, true),
  ('Cloud Storage Usage', 'How do you store your digital files?', 1.15, 2, true),
  ('Cybersecurity Awareness', 'How do you protect your online data?', 1.40, 2, true),
  ('App Download Behavior', 'What makes you download new apps?', 1.20, 2, true),
  ('Tech Support Experiences', 'Share your tech support experiences', 1.25, 2, true),
  ('Wearable Technology', 'Do you use fitness trackers or smartwatches?', 1.30, 2, true),
  ('Online Privacy Concerns', 'How concerned are you about privacy?', 1.35, 2, true),
  ('Email Management Habits', 'How do you manage your emails?', 1.10, 2, true),
  ('Backup Solutions', 'How do you backup your data?', 1.20, 2, true),
  ('Browser Preferences', 'Which web browser do you prefer?', 1.15, 2, true),
  ('Operating System Choice', 'Windows, Mac, or Linux?', 1.25, 2, true),
  ('Tech News Sources', 'Where do you get tech news?', 1.20, 2, true),
  ('Software Updates', 'How do you handle software updates?', 1.10, 2, true),
  ('Digital Assistant Usage', 'Do you use Siri, Alexa, or Google Assistant?', 1.30, 2, true),
  ('Tech Purchase Research', 'How do you research tech purchases?', 1.25, 2, true),

  -- Health & Wellness (100 surveys)
  ('Health & Wellness Survey', 'Share your thoughts on health and wellness products', 1.00, 2, true),
  ('Exercise Routine Survey', 'Tell us about your workout habits', 1.20, 2, true),
  ('Nutrition and Diet Preferences', 'What are your dietary habits?', 1.25, 2, true),
  ('Mental Health Awareness', 'How do you maintain mental wellness?', 1.30, 2, true),
  ('Sleep Quality Study', 'How well do you sleep?', 1.15, 2, true),
  ('Vitamin and Supplement Usage', 'Do you take vitamins or supplements?', 1.10, 2, true),
  ('Fitness App Usage', 'Which fitness apps do you use?', 1.20, 2, true),
  ('Healthcare Provider Satisfaction', 'Rate your healthcare experiences', 1.35, 2, true),
  ('Alternative Medicine Interest', 'Have you tried alternative medicine?', 1.25, 2, true),
  ('Stress Management Techniques', 'How do you manage stress?', 1.30, 2, true),
  ('Gym Membership Survey', 'Do you have a gym membership?', 1.15, 2, true),
  ('Healthy Eating Habits', 'What healthy foods do you eat?', 1.20, 2, true),
  ('Meditation and Mindfulness', 'Do you practice meditation?', 1.25, 2, true),
  ('Dental Care Habits', 'Tell us about your dental hygiene', 1.10, 2, true),
  ('Water Intake Survey', 'How much water do you drink daily?', 1.15, 2, true),
  ('Health Insurance Satisfaction', 'Are you satisfied with your insurance?', 1.30, 2, true),
  ('Preventive Health Measures', 'What preventive care do you practice?', 1.25, 2, true),
  ('Chronic Condition Management', 'How do you manage health conditions?', 1.20, 2, true),
  ('Physical Therapy Experience', 'Have you used physical therapy?', 1.15, 2, true),
  ('Health Goal Setting', 'What are your health goals?', 1.25, 2, true),

  -- Entertainment (100 surveys)
  ('Entertainment Preferences', 'What are your favorite forms of entertainment?', 1.00, 2, true),
  ('Movie Watching Habits', 'How often do you watch movies?', 1.20, 2, true),
  ('Music Streaming Services', 'Which music service do you use?', 1.25, 2, true),
  ('Book Reading Preferences', 'What types of books do you read?', 1.15, 2, true),
  ('Podcast Listening Habits', 'Do you listen to podcasts?', 1.20, 2, true),
  ('Live Event Attendance', 'Do you attend concerts or shows?', 1.30, 2, true),
  ('TV Show Binge Watching', 'What shows have you binge-watched?', 1.25, 2, true),
  ('Video Game Platforms', 'Which gaming platform do you prefer?', 1.35, 2, true),
  ('Theater and Arts', 'Do you attend theater performances?', 1.20, 2, true),
  ('Sports Viewing Habits', 'Which sports do you watch?', 1.15, 2, true),
  ('Hobby and Craft Activities', 'What hobbies do you enjoy?', 1.25, 2, true),
  ('Museum and Gallery Visits', 'Do you visit museums?', 1.20, 2, true),
  ('Comedy Content Preferences', 'What makes you laugh?', 1.10, 2, true),
  ('Documentary Viewing', 'Do you watch documentaries?', 1.15, 2, true),
  ('Board Game Enthusiasm', 'Do you play board games?', 1.20, 2, true),
  ('Outdoor Recreation', 'What outdoor activities do you enjoy?', 1.25, 2, true),
  ('Photography Interest', 'Are you interested in photography?', 1.30, 2, true),
  ('Cooking and Baking', 'Do you enjoy cooking?', 1.20, 2, true),
  ('Gardening Activities', 'Do you have a garden?', 1.15, 2, true),
  ('DIY Projects', 'Do you do DIY projects?', 1.25, 2, true),

  -- Travel & Lifestyle (100 surveys)
  ('Travel & Lifestyle', 'Share your travel experiences and preferences', 1.50, 3, true),
  ('Vacation Planning Habits', 'How do you plan vacations?', 1.30, 2, true),
  ('Hotel vs Airbnb Preferences', 'Where do you prefer to stay?', 1.25, 2, true),
  ('Air Travel Experiences', 'Share your flying experiences', 1.35, 2, true),
  ('Road Trip Preferences', 'Do you enjoy road trips?', 1.20, 2, true),
  ('International Travel', 'Have you traveled internationally?', 1.40, 2, true),
  ('Travel Budget Planning', 'How do you budget for travel?', 1.25, 2, true),
  ('Cruise Ship Experience', 'Have you been on a cruise?', 1.30, 2, true),
  ('Adventure Travel Interest', 'Do you like adventure travel?', 1.35, 2, true),
  ('Travel Booking Methods', 'How do you book travel?', 1.20, 2, true),
  ('Cultural Tourism', 'Do you visit cultural sites?', 1.25, 2, true),
  ('Travel Insurance Usage', 'Do you buy travel insurance?', 1.15, 2, true),
  ('Solo Travel Experience', 'Have you traveled solo?', 1.30, 2, true),
  ('Family Vacation Planning', 'How do you plan family trips?', 1.25, 2, true),
  ('Business Travel Frequency', 'Do you travel for work?', 1.20, 2, true),
  ('Travel Reward Programs', 'Do you use travel rewards?', 1.15, 2, true),
  ('Destination Bucket List', 'Where do you want to travel?', 1.25, 2, true),
  ('Travel Photography', 'Do you take photos while traveling?', 1.20, 2, true),
  ('Local Tourism', 'Do you explore local attractions?', 1.10, 2, true),
  ('Seasonal Travel Preferences', 'When do you prefer to travel?', 1.25, 2, true),

  -- Food & Dining (100 surveys)
  ('Food & Dining Survey', 'Tell us about your food preferences and dining habits', 1.25, 2, true),
  ('Restaurant Dining Frequency', 'How often do you eat out?', 1.20, 2, true),
  ('Fast Food Preferences', 'Which fast food do you prefer?', 1.10, 2, true),
  ('Fine Dining Experiences', 'Do you enjoy fine dining?', 1.35, 2, true),
  ('Food Delivery Service Usage', 'Which delivery apps do you use?', 1.25, 2, true),
  ('Dietary Restrictions', 'Do you have dietary restrictions?', 1.20, 2, true),
  ('Cooking at Home Frequency', 'How often do you cook?', 1.15, 2, true),
  ('Meal Planning Habits', 'Do you plan your meals?', 1.20, 2, true),
  ('Ethnic Food Preferences', 'Which cuisines do you enjoy?', 1.25, 2, true),
  ('Coffee and Tea Habits', 'Are you a coffee or tea person?', 1.10, 2, true),
  ('Dessert Preferences', 'What are your favorite desserts?', 1.15, 2, true),
  ('Food Subscription Boxes', 'Do you use meal kit services?', 1.30, 2, true),
  ('Organic Food Preferences', 'Do you buy organic food?', 1.25, 2, true),
  ('Vegetarian/Vegan Interest', 'Have you tried plant-based diets?', 1.20, 2, true),
  ('Snacking Habits', 'What snacks do you enjoy?', 1.10, 2, true),
  ('Restaurant Review Habits', 'Do you leave restaurant reviews?', 1.15, 2, true),
  ('Food Allergies and Sensitivities', 'Do you have food allergies?', 1.20, 2, true),
  ('Breakfast Preferences', 'What do you eat for breakfast?', 1.15, 2, true),
  ('Beverage Preferences', 'What are your favorite drinks?', 1.10, 2, true),
  ('Food Waste Concerns', 'How do you reduce food waste?', 1.25, 2, true),

  -- Work & Career (100 surveys)
  ('Work & Productivity', 'Share insights about your work environment and productivity', 1.50, 2, true),
  ('Remote Work Experience', 'Do you work from home?', 1.30, 2, true),
  ('Career Satisfaction Survey', 'Are you satisfied with your career?', 1.35, 2, true),
  ('Workplace Culture', 'How would you describe your workplace?', 1.25, 2, true),
  ('Professional Development', 'How do you develop your skills?', 1.30, 2, true),
  ('Work-Life Balance', 'How do you balance work and life?', 1.35, 2, true),
  ('Job Search Methods', 'How do you look for jobs?', 1.20, 2, true),
  ('Salary Satisfaction', 'Are you satisfied with your pay?', 1.40, 2, true),
  ('Employee Benefits Importance', 'Which benefits matter most?', 1.30, 2, true),
  ('Commute Experience', 'How is your commute to work?', 1.15, 2, true),
  ('Office Environment Preferences', 'Do you prefer open or closed offices?', 1.20, 2, true),
  ('Meeting Productivity', 'How productive are meetings?', 1.25, 2, true),
  ('Technology Tools at Work', 'Which work tools do you use?', 1.30, 2, true),
  ('Leadership Satisfaction', 'How satisfied are you with management?', 1.35, 2, true),
  ('Team Collaboration', 'How well does your team collaborate?', 1.25, 2, true),
  ('Career Advancement Opportunities', 'Can you advance in your career?', 1.30, 2, true),
  ('Freelance Work Experience', 'Have you done freelance work?', 1.25, 2, true),
  ('Side Hustle Survey', 'Do you have a side business?', 1.20, 2, true),
  ('Continuing Education', 'Are you pursuing further education?', 1.30, 2, true),
  ('Workplace Stress Levels', 'How stressed are you at work?', 1.35, 2, true),

  -- Finance & Banking (100 surveys)
  ('Banking Preferences Survey', 'Tell us about your banking habits', 1.30, 2, true),
  ('Credit Card Usage', 'How do you use credit cards?', 1.25, 2, true),
  ('Savings Habits', 'How much do you save monthly?', 1.35, 2, true),
  ('Investment Preferences', 'Do you invest your money?', 1.40, 2, true),
  ('Budgeting Methods', 'How do you budget?', 1.25, 2, true),
  ('Online Banking Usage', 'Do you use online banking?', 1.20, 2, true),
  ('Financial Goal Setting', 'What are your financial goals?', 1.30, 2, true),
  ('Retirement Planning', 'Are you planning for retirement?', 1.35, 2, true),
  ('Mobile Payment Apps', 'Which payment apps do you use?', 1.25, 2, true),
  ('Cryptocurrency Interest', 'Are you interested in crypto?', 1.30, 2, true),
  ('Debt Management', 'How do you manage debt?', 1.35, 2, true),
  ('Insurance Coverage', 'What insurance do you have?', 1.25, 2, true),
  ('Financial Advisor Usage', 'Do you use a financial advisor?', 1.30, 2, true),
  ('Emergency Fund Survey', 'Do you have an emergency fund?', 1.25, 2, true),
  ('Tax Preparation Methods', 'How do you prepare taxes?', 1.35, 2, true),
  ('Stock Market Interest', 'Do you follow the stock market?', 1.30, 2, true),
  ('Real Estate Investment', 'Have you invested in real estate?', 1.40, 2, true),
  ('Financial Literacy', 'How financially literate are you?', 1.25, 2, true),
  ('Side Income Sources', 'Do you have additional income?', 1.30, 2, true),
  ('Charitable Giving', 'Do you donate to charities?', 1.20, 2, true),

  -- Education (100 surveys)
  ('Education Background Survey', 'Tell us about your education', 1.25, 2, true),
  ('Online Learning Experience', 'Have you taken online courses?', 1.30, 2, true),
  ('Student Loan Status', 'Do you have student loans?', 1.35, 2, true),
  ('Learning Style Preferences', 'How do you learn best?', 1.20, 2, true),
  ('Educational Technology', 'Which edtech tools do you use?', 1.25, 2, true),
  ('Professional Certification', 'Have you earned certifications?', 1.30, 2, true),
  ('Parental Education Involvement', 'How involved are you in kids education?', 1.25, 2, true),
  ('Library Usage', 'Do you use public libraries?', 1.15, 2, true),
  ('Language Learning', 'Are you learning new languages?', 1.30, 2, true),
  ('Tutoring Experience', 'Have you used tutoring services?', 1.25, 2, true),
  ('College Selection Process', 'How did you choose your college?', 1.30, 2, true),
  ('Study Habits Survey', 'What are your study habits?', 1.20, 2, true),
  ('Educational YouTube Channels', 'Do you watch educational content?', 1.15, 2, true),
  ('Homeschooling Opinions', 'What do you think about homeschooling?', 1.25, 2, true),
  ('Career vs Education Path', 'Did education match your career?', 1.30, 2, true),
  ('Educational Expenses', 'How much do you spend on education?', 1.35, 2, true),
  ('Learning Motivation', 'What motivates you to learn?', 1.20, 2, true),
  ('School Choice Factors', 'What matters in choosing schools?', 1.25, 2, true),
  ('Adult Education Programs', 'Are you in adult education?', 1.30, 2, true),
  ('Educational Resources', 'What learning resources do you use?', 1.25, 2, true),

  -- Automotive (100 surveys)
  ('Vehicle Ownership Survey', 'Tell us about your vehicle', 1.30, 2, true),
  ('Car Purchase Decision', 'How do you choose a car?', 1.35, 2, true),
  ('Electric Vehicle Interest', 'Are you interested in EVs?', 1.40, 2, true),
  ('Car Maintenance Habits', 'How do you maintain your car?', 1.25, 2, true),
  ('Ride-Sharing Usage', 'Do you use Uber or Lyft?', 1.20, 2, true),
  ('Auto Insurance Satisfaction', 'Are you happy with your insurance?', 1.30, 2, true),
  ('Fuel Efficiency Importance', 'How important is fuel efficiency?', 1.25, 2, true),
  ('Car Safety Features', 'Which safety features matter most?', 1.35, 2, true),
  ('Vehicle Leasing vs Buying', 'Do you lease or buy?', 1.30, 2, true),
  ('Car Brand Preferences', 'Which car brands do you prefer?', 1.25, 2, true),
  ('Used vs New Car', 'Do you prefer new or used cars?', 1.30, 2, true),
  ('Autonomous Vehicle Opinion', 'What do you think about self-driving cars?', 1.35, 2, true),
  ('Car Wash Frequency', 'How often do you wash your car?', 1.15, 2, true),
  ('Long Distance Driving', 'Do you take long road trips?', 1.20, 2, true),
  ('Parking Challenges', 'What parking challenges do you face?', 1.25, 2, true),
  ('Car Technology Features', 'Which tech features do you use?', 1.30, 2, true),
  ('Traffic and Commuting', 'How bad is your commute traffic?', 1.20, 2, true),
  ('Car Loan Experience', 'Have you financed a car?', 1.30, 2, true),
  ('Driving Habits', 'How would you describe your driving?', 1.15, 2, true),
  ('Vehicle Upgrades', 'Do you upgrade your vehicle?', 1.25, 2, true),

  -- Home & Family (100 surveys)
  ('Home Ownership Survey', 'Do you own or rent your home?', 1.30, 2, true),
  ('Family Size and Structure', 'Tell us about your family', 1.20, 2, true),
  ('Home Improvement Projects', 'What home projects have you done?', 1.35, 2, true),
  ('Parenting Challenges', 'What parenting challenges do you face?', 1.25, 2, true),
  ('Smart Home Technology', 'Do you have smart home devices?', 1.30, 2, true),
  ('Home Security Systems', 'How do you secure your home?', 1.35, 2, true),
  ('Interior Design Preferences', 'What is your home style?', 1.25, 2, true),
  ('Pet Ownership Survey', 'Do you have pets?', 1.20, 2, true),
  ('Household Chores Distribution', 'How are chores divided?', 1.15, 2, true),
  ('Home Energy Efficiency', 'How energy efficient is your home?', 1.30, 2, true),
  ('Furniture Shopping Habits', 'Where do you buy furniture?', 1.25, 2, true),
  ('Moving and Relocation', 'Have you moved recently?', 1.30, 2, true),
  ('Childcare Arrangements', 'What childcare do you use?', 1.35, 2, true),
  ('Home Office Setup', 'Do you have a home office?', 1.25, 2, true),
  ('Mortgage and Financing', 'How did you finance your home?', 1.40, 2, true),
  ('Neighborhood Satisfaction', 'Do you like your neighborhood?', 1.20, 2, true),
  ('Home Appliance Preferences', 'Which appliances do you prefer?', 1.30, 2, true),
  ('Yard and Garden Maintenance', 'How do you maintain your yard?', 1.25, 2, true),
  ('Home Insurance Coverage', 'What home insurance do you have?', 1.30, 2, true),
  ('Family Activity Planning', 'What activities do you do together?', 1.20, 2, true)
on conflict do nothing;
