-- Continue adding surveys to reach 1000 total
insert into public.surveys (title, description, reward_amount, estimated_time_minutes, is_active)
values
  -- Additional Consumer Surveys (200 more)
  ('Online Marketplace Preferences', 'Amazon, eBay, or other platforms?', 1.20, 2, true),
  ('Product Unboxing Experience', 'How important is packaging?', 1.15, 2, true),
  ('Influencer Marketing Impact', 'Do influencers affect your purchases?', 1.25, 2, true),
  ('Black Friday Shopping', 'Do you shop on Black Friday?', 1.30, 2, true),
  ('Warranty and Protection Plans', 'Do you buy extended warranties?', 1.20, 2, true),
  ('Customer Reviews Importance', 'Do you read reviews before buying?', 1.25, 2, true),
  ('Bulk Purchase Habits', 'Do you buy in bulk?', 1.15, 2, true),
  ('Secondhand Shopping', 'Do you buy used items?', 1.20, 2, true),
  ('Store Brand vs Name Brand', 'Do you prefer store brands?', 1.10, 2, true),
  ('Shopping Cart Abandonment', 'Why do you abandon online carts?', 1.25, 2, true),
  ('Flash Sale Participation', 'Do you shop flash sales?', 1.20, 2, true),
  ('Product Comparison Tools', 'Which comparison tools do you use?', 1.15, 2, true),
  ('Cashback and Rewards', 'Do you use cashback apps?', 1.25, 2, true),
  ('Same-Day Delivery Usage', 'Do you pay for fast delivery?', 1.30, 2, true),
  ('Store Pickup vs Delivery', 'Do you prefer pickup or delivery?', 1.15, 2, true),
  ('Shopping List Habits', 'Do you make shopping lists?', 1.10, 2, true),
  ('Impulse Purchase Triggers', 'What triggers impulse buys?', 1.20, 2, true),
  ('Gift Card Usage', 'Do you use gift cards?', 1.15, 2, true),
  ('Product Demo Interest', 'Do you like product demos?', 1.20, 2, true),
  ('Virtual Shopping Experience', 'Have you tried AR/VR shopping?', 1.35, 2, true),
  ('Sustainable Shopping Habits', 'Do you buy eco-friendly products?', 1.30, 2, true),
  ('Local Business Support', 'Do you shop local?', 1.25, 2, true),
  ('Auction Site Usage', 'Do you use auction websites?', 1.20, 2, true),
  ('Daily Deals Websites', 'Do you use Groupon or similar?', 1.15, 2, true),
  ('Product Recommendation Trust', 'Do you trust product recommendations?', 1.25, 2, true),
  ('Retail Store Experience', 'What makes a good retail experience?', 1.30, 2, true),
  ('Payment Method Preferences', 'How do you prefer to pay?', 1.20, 2, true),
  ('Buy Now Pay Later Services', 'Do you use Afterpay or Klarna?', 1.25, 2, true),
  ('Product Customization', 'Do you customize products?', 1.30, 2, true),
  ('Shopping During Sales', 'When do you shop for deals?', 1.15, 2, true),
  ('Product Size and Fit', 'How do you determine size online?', 1.20, 2, true),
  ('Shopping Time Preferences', 'When do you prefer to shop?', 1.10, 2, true),
  ('Brand Loyalty Factors', 'What makes you loyal to brands?', 1.25, 2, true),
  ('Advertising Influence', 'Do ads influence your purchases?', 1.20, 2, true),
  ('Shopping Companion Preferences', 'Do you shop alone or with others?', 1.15, 2, true),
  ('Product Photography Impact', 'How important are product photos?', 1.20, 2, true),
  ('Seasonal Product Purchases', 'What seasonal items do you buy?', 1.25, 2, true),
  ('Limited Edition Products', 'Do you buy limited editions?', 1.30, 2, true),
  ('Shopping Budget Tracking', 'Do you track shopping expenses?', 1.20, 2, true),
  ('Checkout Process Preferences', 'What makes checkout easy?', 1.25, 2, true),
  ('Post-Purchase Satisfaction', 'How often are you satisfied?', 1.15, 2, true),
  ('Shopping Newsletter Subscriptions', 'Do you subscribe to store emails?', 1.10, 2, true),
  ('Product Availability Notifications', 'Do you use back-in-stock alerts?', 1.20, 2, true),
  ('Shopping App Features', 'What app features do you value?', 1.25, 2, true),
  ('Price Drop Alerts', 'Do you use price tracking?', 1.20, 2, true),
  ('Bundle Purchase Preferences', 'Do you buy product bundles?', 1.15, 2, true),
  ('Trial and Sample Products', 'Do you try samples before buying?', 1.20, 2, true),
  ('Shopping Experience Personalization', 'Do you like personalized shopping?', 1.25, 2, true),
  ('Product Video Reviews', 'Do you watch video reviews?', 1.20, 2, true),
  ('Wishlist and Save for Later', 'Do you use wishlists?', 1.15, 2, true),
  ('Shopping Social Sharing', 'Do you share purchases on social media?', 1.20, 2, true),
  ('Multi-Device Shopping', 'Do you shop across devices?', 1.25, 2, true),
  ('Shopping During Work Hours', 'Do you shop during work?', 1.15, 2, true),
  ('Product Recall Awareness', 'How do you stay informed about recalls?', 1.20, 2, true),
  ('Charitable Shopping Options', 'Do you choose charity-linked products?', 1.25, 2, true),
  ('Shopping Habit Changes', 'How have your habits changed?', 1.20, 2, true),
  ('Product Durability Importance', 'How important is product longevity?', 1.30, 2, true),
  ('Shopping Deal Sharing', 'Do you share deals with others?', 1.15, 2, true),
  ('Shopping Time Investment', 'How much time do you spend shopping?', 1.20, 2, true),
  ('Product Trend Following', 'Do you follow trends?', 1.25, 2, true),
  ('Shopping Anxiety Survey', 'Does shopping stress you?', 1.20, 2, true),
  ('Product Quality vs Price', 'Quality or price - which matters?', 1.25, 2, true),
  ('Shopping Entertainment Value', 'Do you shop for entertainment?', 1.15, 2, true),
  ('Product Research Depth', 'How thoroughly do you research?', 1.20, 2, true),
  ('Shopping Decision Speed', 'Are you a quick or slow shopper?', 1.15, 2, true),
  ('Product Packaging Waste Concerns', 'Do you worry about packaging?', 1.25, 2, true),
  ('Shopping With Children', 'How does shopping with kids affect you?', 1.20, 2, true),
  ('Product Assembly Preferences', 'Do you mind assembling products?', 1.15, 2, true),
  ('Shopping Goal Achievement', 'Do you stick to shopping goals?', 1.20, 2, true),
  ('Product Innovation Interest', 'Do you buy innovative products?', 1.30, 2, true),
  ('Shopping Security Concerns', 'How concerned are you about security?', 1.25, 2, true),
  ('Product Expiration Date Checking', 'Do you check expiration dates?', 1.15, 2, true),
  ('Shopping Mood Influence', 'Does your mood affect shopping?', 1.20, 2, true),
  ('Product Storage Solutions', 'How do you store purchases?', 1.15, 2, true),
  ('Shopping Frequency Changes', 'How often do you shop now vs before?', 1.20, 2, true),
  ('Product Feature Priorities', 'Which features matter most?', 1.25, 2, true),
  ('Shopping Communication Preferences', 'How do you want stores to contact you?', 1.20, 2, true),
  ('Product Lifecycle Awareness', 'Are you aware of product lifecycles?', 1.25, 2, true),
  ('Shopping Cart Size Preferences', 'Physical or digital cart size?', 1.10, 2, true),
  ('Product Material Preferences', 'What materials do you prefer?', 1.20, 2, true),
  ('Shopping Interruption Tolerance', 'How do you handle interruptions?', 1.15, 2, true),
  ('Product Version Upgrades', 'Do you upgrade to new versions?', 1.25, 2, true),
  ('Shopping Subscription Fatigue', 'Too many subscriptions?', 1.20, 2, true),
  ('Product Color Choices', 'How important is color selection?', 1.15, 2, true),
  ('Shopping Learning Curve', 'How quickly do you learn new shops?', 1.10, 2, true),
  ('Product Disposal Methods', 'How do you dispose of old items?', 1.20, 2, true),
  ('Shopping Value Perception', 'What represents value to you?', 1.25, 2, true),
  ('Product Brand Recognition', 'How important is brand recognition?', 1.20, 2, true),
  ('Shopping Schedule Flexibility', 'When is your ideal shopping time?', 1.15, 2, true),
  ('Product Maintenance Requirements', 'Do you consider maintenance needs?', 1.20, 2, true),
  ('Shopping Guilt or Regret', 'Do you feel guilt after shopping?', 1.15, 2, true),
  ('Product Multi-Use Capabilities', 'Do you prefer multi-purpose items?', 1.25, 2, true),
  ('Shopping Payment Security', 'How do you ensure payment security?', 1.30, 2, true),
  ('Product Testing Before Purchase', 'Do you test before buying?', 1.20, 2, true),
  ('Shopping Accessibility Needs', 'What accessibility features help you?', 1.25, 2, true),
  ('Product Origin Importance', 'Does where its made matter?', 1.20, 2, true),
  ('Shopping Competition Comparison', 'Do you compare competitor prices?', 1.25, 2, true),
  ('Product Instructions Clarity', 'How important are clear instructions?', 1.15, 2, true),
  ('Shopping Membership Benefits', 'Are memberships worth it?', 1.30, 2, true),
  
  -- More Technology Surveys (200 more)
  ('5G Technology Adoption', 'Are you using 5G?', 1.35, 2, true),
  ('Tablet Usage Patterns', 'Do you use tablets?', 1.25, 2, true),
  ('Virtual Reality Interest', 'Have you tried VR?', 1.40, 2, true),
  ('Augmented Reality Apps', 'Do you use AR apps?', 1.30, 2, true),
  ('Voice Search Usage', 'Do you use voice search?', 1.20, 2, true),
  ('QR Code Scanning', 'How often do you scan QR codes?', 1.15, 2, true),
  ('Password Manager Usage', 'Do you use password managers?', 1.25, 2, true),
  ('Two-Factor Authentication', 'Do you use 2FA?', 1.30, 2, true),
  ('VPN Usage Patterns', 'Do you use a VPN?', 1.35, 2, true),
  ('Ad Blocker Preferences', 'Do you block ads?', 1.20, 2, true),
  ('Screen Time Awareness', 'How much screen time do you have?', 1.15, 2, true),
  ('Digital Detox Interest', 'Have you done a digital detox?', 1.25, 2, true),
  ('Smartphone Addiction Concerns', 'Are you concerned about phone addiction?', 1.20, 2, true),
  ('App Notification Management', 'How do you manage notifications?', 1.15, 2, true),
  ('Dark Mode Preferences', 'Do you use dark mode?', 1.10, 2, true),
  ('Bluetooth Device Usage', 'What Bluetooth devices do you use?', 1.20, 2, true),
  ('Wireless Charging Adoption', 'Do you use wireless charging?', 1.25, 2, true),
  ('USB-C Transition', 'Have you switched to USB-C?', 1.20, 2, true),
  ('Phone Case Preferences', 'Do you use a phone case?', 1.10, 2, true),
  ('Screen Protector Usage', 'Do you use screen protectors?', 1.15, 2, true),
  ('Phone Battery Life Satisfaction', 'How is your battery life?', 1.25, 2, true),
  ('Phone Storage Management', 'How do you manage phone storage?', 1.20, 2, true),
  ('Mobile Photo Organization', 'How do you organize photos?', 1.25, 2, true),
  ('Contact Management Methods', 'How do you manage contacts?', 1.15, 2, true),
  ('Calendar App Usage', 'Which calendar app do you use?', 1.20, 2, true),
  ('Note-Taking App Preferences', 'How do you take digital notes?', 1.25, 2, true),
  ('To-Do List Apps', 'Do you use task management apps?', 1.20, 2, true),
  ('File Sharing Methods', 'How do you share files?', 1.25, 2, true),
  ('Video Conferencing Tools', 'Which video call apps do you use?', 1.30, 2, true),
  ('Messaging App Preferences', 'WhatsApp, iMessage, or other?', 1.20, 2, true),
  ('Email App Preferences', 'Which email app do you prefer?', 1.15, 2, true),
  ('Spam Email Management', 'How do you handle spam?', 1.20, 2, true),
  ('Digital Signature Usage', 'Do you use digital signatures?', 1.25, 2, true),
  ('PDF Reader Preferences', 'Which PDF reader do you use?', 1.15, 2, true),
  ('Screenshot Frequency', 'How often do you take screenshots?', 1.10, 2, true),
  ('Voice Message Usage', 'Do you send voice messages?', 1.20, 2, true),
  ('GIF and Emoji Usage', 'Do you use GIFs and emojis?', 1.15, 2, true),
  ('Keyboard vs Voice Typing', 'Do you use voice typing?', 1.20, 2, true),
  ('Autocorrect Satisfaction', 'How do you feel about autocorrect?', 1.15, 2, true),
  ('Phone Upgrade Frequency', 'How often do you upgrade phones?', 1.30, 2, true),
  ('Old Device Disposal', 'What do you do with old devices?', 1.25, 2, true),
  ('Device Repair vs Replace', 'Do you repair or replace?', 1.30, 2, true),
  ('Tech Support Channels', 'How do you get tech support?', 1.20, 2, true),
  ('Online Tutorial Usage', 'Do you watch tech tutorials?', 1.25, 2, true),
  ('Technology Frustration Levels', 'What frustrates you about tech?', 1.20, 2, true),
  ('New Technology Adoption Speed', 'Are you an early adopter?', 1.30, 2, true),
  ('Tech Product Review Trust', 'Do you trust tech reviews?', 1.25, 2, true),
  ('Open Source Software Usage', 'Do you use open source software?', 1.30, 2, true),
  ('Software Piracy Opinions', 'What do you think about piracy?', 1.20, 2, true),
  ('Digital Rights Management', 'How do you feel about DRM?', 1.25, 2, true),
  ('Internet Speed Satisfaction', 'Are you happy with internet speed?', 1.30, 2, true),
  ('WiFi vs Mobile Data', 'Do you prefer WiFi or mobile data?', 1.20, 2, true),
  ('Data Usage Monitoring', 'Do you monitor data usage?', 1.25, 2, true),
  ('Unlimited Data Plans', 'Do you have unlimited data?', 1.20, 2, true),
  ('Roaming Data Usage', 'How do you handle roaming?', 1.25, 2, true),
  ('Public WiFi Security', 'Do you use public WiFi?', 1.30, 2, true),
  ('Network Coverage Satisfaction', 'How is your network coverage?', 1.20, 2, true),
  ('5G Home Internet', 'Are you using 5G home internet?', 1.35, 2, true),
  ('Smart Speaker Usage', 'Do you have smart speakers?', 1.30, 2, true),
  ('Voice Assistant Commands', 'What voice commands do you use?', 1.25, 2, true),
  ('Smart Lighting Systems', 'Do you have smart lights?', 1.30, 2, true),
  ('Smart Thermostat Usage', 'Do you have a smart thermostat?', 1.35, 2, true),
  ('Smart Lock Security', 'Do you use smart door locks?', 1.40, 2, true),
  ('Home Security Cameras', 'Do you have security cameras?', 1.35, 2, true),
  ('Robot Vacuum Experience', 'Do you have a robot vacuum?', 1.30, 2, true),
  ('Smart Kitchen Appliances', 'Do you have smart kitchen devices?', 1.35, 2, true),
  ('Home Automation Routines', 'Do you automate home tasks?', 1.30, 2, true),
  ('IoT Device Security Concerns', 'Are you worried about IoT security?', 1.35, 2, true),
  ('E-Reader Usage', 'Do you use an e-reader?', 1.25, 2, true),
  ('Digital vs Physical Books', 'Do you prefer digital or physical?', 1.20, 2, true),
  ('Audiobook Listening', 'Do you listen to audiobooks?', 1.25, 2, true),
  ('Digital Magazine Subscriptions', 'Do you read digital magazines?', 1.20, 2, true),
  ('News App Preferences', 'Which news apps do you use?', 1.25, 2, true),
  ('RSS Feed Reader Usage', 'Do you use RSS readers?', 1.20, 2, true),
  ('Bookmark Management', 'How do you manage bookmarks?', 1.15, 2, true),
  ('Tab Management Strategies', 'How many browser tabs do you have?', 1.20, 2, true),
  ('Browser Extension Usage', 'Which extensions do you use?', 1.25, 2, true),
  ('Private Browsing Usage', 'Do you use incognito mode?', 1.20, 2, true),
  ('Cookie Management', 'How do you handle cookies?', 1.25, 2, true),
  ('Browser History Clearing', 'Do you clear browsing history?', 1.15, 2, true),
  ('Homepage Preferences', 'What is your browser homepage?', 1.10, 2, true),
  ('Search Engine Preferences', 'Which search engine do you use?', 1.20, 2, true),
  ('Online Privacy Tools', 'What privacy tools do you use?', 1.30, 2, true),
  ('Data Tracking Concerns', 'How concerned are you about tracking?', 1.35, 2, true),
  ('GDPR Awareness', 'Are you aware of GDPR?', 1.25, 2, true),
  ('Terms of Service Reading', 'Do you read terms of service?', 1.15, 2, true),
  ('App Permission Management', 'Do you review app permissions?', 1.25, 2, true),
  ('Location Services Usage', 'When do you enable location?', 1.20, 2, true),
  ('Biometric Authentication', 'Do you use fingerprint or face ID?', 1.30, 2, true),
  ('Device Lost or Stolen Experience', 'Have you lost a device?', 1.25, 2, true),
  ('Remote Device Wiping', 'Do you have remote wipe enabled?', 1.30, 2, true),
  ('Device Backup Frequency', 'How often do you backup?', 1.25, 2, true),
  ('Cloud Backup Services', 'Which cloud backup do you use?', 1.30, 2, true),
  ('External Drive Usage', 'Do you use external drives?', 1.20, 2, true),
  ('Data Recovery Experience', 'Have you recovered lost data?', 1.25, 2, true),
  ('File Sync Services', 'Do you use file syncing?', 1.30, 2, true)
on conflict do nothing;
