-- Final batch to complete 1000 surveys
-- Adding 400 more diverse surveys
insert into public.surveys (title, description, reward_amount, estimated_time_minutes, is_active)
values
  -- Lifestyle & Personal Development (100 more)
  ('Morning Routine Survey', 'Tell us about your morning habits', 1.20, 2, true),
  ('Evening Routine Survey', 'What is your bedtime routine?', 1.20, 2, true),
  ('Time Management Skills', 'How do you manage your time?', 1.25, 2, true),
  ('Goal Setting Methods', 'How do you set and track goals?', 1.30, 2, true),
  ('Habit Formation Strategies', 'How do you build new habits?', 1.25, 2, true),
  ('Procrastination Patterns', 'Do you procrastinate?', 1.20, 2, true),
  ('Personal Organization Systems', 'How do you stay organized?', 1.25, 2, true),
  ('Journaling Habits', 'Do you keep a journal?', 1.20, 2, true),
  ('Reading Frequency', 'How often do you read?', 1.15, 2, true),
  ('Self-Improvement Interest', 'What self-improvement topics interest you?', 1.25, 2, true),
  ('Personal Finance Education', 'How did you learn about finance?', 1.30, 2, true),
  ('Life Coach Interest', 'Would you hire a life coach?', 1.25, 2, true),
  ('Motivational Content Consumption', 'Do you consume motivational content?', 1.20, 2, true),
  ('Personal Brand Development', 'Are you building a personal brand?', 1.30, 2, true),
  ('Networking Strategies', 'How do you network?', 1.25, 2, true),
  ('Public Speaking Comfort', 'How comfortable are you speaking publicly?', 1.20, 2, true),
  ('Conflict Resolution Skills', 'How do you handle conflicts?', 1.25, 2, true),
  ('Emotional Intelligence Awareness', 'How emotionally intelligent are you?', 1.30, 2, true),
  ('Leadership Experience', 'Have you been in leadership roles?', 1.25, 2, true),
  ('Teamwork Preferences', 'Do you prefer teamwork or solo work?', 1.20, 2, true),
  ('Decision Making Process', 'How do you make important decisions?', 1.25, 2, true),
  ('Risk Taking Attitude', 'Are you a risk taker?', 1.30, 2, true),
  ('Failure and Learning', 'How do you handle failure?', 1.25, 2, true),
  ('Success Definition', 'How do you define success?', 1.20, 2, true),
  ('Life Satisfaction Survey', 'How satisfied are you with life?', 1.30, 2, true),
  ('Personal Values Identification', 'What are your core values?', 1.25, 2, true),
  ('Spiritual Practices', 'Do you have spiritual practices?', 1.20, 2, true),
  ('Mindset and Attitude', 'Fixed or growth mindset?', 1.25, 2, true),
  ('Personal Boundaries', 'How do you set boundaries?', 1.30, 2, true),
  ('Work Ethic Survey', 'How would you describe your work ethic?', 1.20, 2, true),
  ('Mentorship Experience', 'Have you had a mentor?', 1.25, 2, true),
  ('Teaching and Knowledge Sharing', 'Do you teach or mentor others?', 1.25, 2, true),
  ('Volunteerism and Community Service', 'Do you volunteer?', 1.20, 2, true),
  ('Environmental Consciousness', 'How environmentally conscious are you?', 1.30, 2, true),
  ('Sustainability Practices', 'What sustainable practices do you follow?', 1.25, 2, true),
  ('Minimalism Interest', 'Are you interested in minimalism?', 1.25, 2, true),
  ('Decluttering Habits', 'Do you declutter regularly?', 1.20, 2, true),
  ('Quality vs Quantity Philosophy', 'Do you prefer quality or quantity?', 1.25, 2, true),
  ('Present Moment Awareness', 'How present are you in the moment?', 1.20, 2, true),
  ('Gratitude Practice', 'Do you practice gratitude?', 1.25, 2, true),
  ('Forgiveness and Letting Go', 'Can you forgive easily?', 1.20, 2, true),
  ('Personal Growth Mindset', 'How committed are you to growth?', 1.30, 2, true),
  ('Authenticity and Self-Expression', 'How authentic are you?', 1.25, 2, true),
  ('Comfort Zone Expansion', 'Do you push your comfort zone?', 1.30, 2, true),
  ('Fear Management', 'How do you manage fear?', 1.25, 2, true),
  ('Confidence Levels', 'How confident are you?', 1.20, 2, true),
  ('Self-Care Routines', 'What self-care do you practice?', 1.25, 2, true),
  ('Alone Time Needs', 'How much alone time do you need?', 1.20, 2, true),
  ('Social Energy Levels', 'Are you introverted or extroverted?', 1.20, 2, true),
  ('Personality Type Awareness', 'Do you know your personality type?', 1.25, 2, true),
  ('Strengths and Weaknesses', 'What are your strengths?', 1.20, 2, true),
  ('Personal Development Investment', 'How much do you invest in development?', 1.30, 2, true),
  ('Learning Style Preferences', 'How do you learn best?', 1.20, 2, true),
  ('Feedback Reception', 'How do you handle criticism?', 1.25, 2, true),
  ('Change Adaptation', 'How well do you adapt to change?', 1.25, 2, true),
  ('Future Planning', 'How far ahead do you plan?', 1.20, 2, true),
  ('Legacy Thoughts', 'What legacy do you want to leave?', 1.30, 2, true),
  ('Life Purpose Understanding', 'Have you found your purpose?', 1.35, 2, true),
  ('Bucket List Progress', 'What is on your bucket list?', 1.25, 2, true),
  ('Regret Analysis', 'What do you regret?', 1.20, 2, true),
  ('Happiness Sources', 'What makes you happy?', 1.25, 2, true),
  ('Stress Sources', 'What stresses you most?', 1.25, 2, true),
  ('Coping Mechanisms', 'How do you cope with stress?', 1.30, 2, true),
  ('Support System Quality', 'Do you have good support?', 1.25, 2, true),
  ('Friendship Quality', 'Are you satisfied with friendships?', 1.20, 2, true),
  ('Family Relationship Quality', 'How are your family relationships?', 1.25, 2, true),
  ('Romantic Relationship Status', 'What is your relationship status?', 1.20, 2, true),
  ('Communication Skills', 'How well do you communicate?', 1.25, 2, true),
  ('Active Listening Habits', 'Are you a good listener?', 1.20, 2, true),
  ('Empathy Levels', 'How empathetic are you?', 1.25, 2, true),
  ('Compassion Practice', 'Do you practice compassion?', 1.20, 2, true),
  ('Kindness Acts', 'Do you perform random acts of kindness?', 1.25, 2, true),
  ('Generosity Survey', 'How generous are you?', 1.20, 2, true),
  ('Patience Levels', 'How patient are you?', 1.20, 2, true),
  ('Perseverance Survey', 'How persistent are you?', 1.25, 2, true),
  ('Resilience Assessment', 'How resilient are you?', 1.30, 2, true),
  ('Optimism vs Pessimism', 'Are you optimistic or pessimistic?', 1.20, 2, true),
  ('Humor and Laughter', 'How often do you laugh?', 1.15, 2, true),
  ('Play and Fun', 'Do you make time for fun?', 1.20, 2, true),
  ('Spontaneity Levels', 'How spontaneous are you?', 1.25, 2, true),
  ('Adventure Seeking', 'Do you seek adventures?', 1.30, 2, true),
  ('Novelty Appreciation', 'Do you enjoy new experiences?', 1.25, 2, true),
  ('Routine vs Variety', 'Do you prefer routine or variety?', 1.20, 2, true),
  ('Flexibility Assessment', 'How flexible are you?', 1.20, 2, true),
  ('Perfectionism Tendencies', 'Are you a perfectionist?', 1.25, 2, true),
  ('Self-Criticism Levels', 'How self-critical are you?', 1.25, 2, true),
  ('Self-Compassion Practice', 'Do you practice self-compassion?', 1.30, 2, true),
  ('Body Image Perception', 'How do you feel about your body?', 1.25, 2, true),
  ('Physical Health Priority', 'How much do you prioritize health?', 1.30, 2, true),
  ('Mental Health Priority', 'How much do you prioritize mental health?', 1.35, 2, true),
  ('Life Balance Achievement', 'Do you feel balanced?', 1.25, 2, true),
  ('Burnout Prevention', 'How do you prevent burnout?', 1.30, 2, true),
  ('Energy Management', 'How do you manage your energy?', 1.25, 2, true),
  ('Focus and Concentration', 'How well can you focus?', 1.25, 2, true),
  ('Distraction Management', 'How do you handle distractions?', 1.20, 2, true),
  ('Multitasking Ability', 'Can you multitask effectively?', 1.20, 2, true),
  ('Single-Tasking Preference', 'Do you prefer single-tasking?', 1.20, 2, true),
  ('Productivity Systems', 'What productivity systems do you use?', 1.30, 2, true),

  -- Random Interesting Topics (300 more to reach 1000)
  ('Weather Preferences Survey', 'What weather do you prefer?', 1.15, 2, true),
  ('Seasonal Favorite', 'What is your favorite season?', 1.10, 2, true),
  ('Climate Change Awareness', 'How concerned are you about climate?', 1.35, 2, true),
  ('Renewable Energy Support', 'Do you support renewable energy?', 1.30, 2, true),
  ('Recycling Habits', 'How often do you recycle?', 1.20, 2, true),
  ('Plastic Usage Reduction', 'Are you reducing plastic use?', 1.25, 2, true),
  ('Water Conservation Efforts', 'Do you conserve water?', 1.20, 2, true),
  ('Energy Conservation', 'How do you save energy?', 1.25, 2, true),
  ('Composting Practice', 'Do you compost?', 1.20, 2, true),
  ('Local Food Sourcing', 'Do you buy local food?', 1.25, 2, true),
  ('Farmers Market Shopping', 'Do you shop at farmers markets?', 1.20, 2, true),
  ('Community Supported Agriculture', 'Do you participate in CSA?', 1.25, 2, true),
  ('Urban Gardening Interest', 'Are you interested in urban gardening?', 1.30, 2, true),
  ('Plant-Based Diet Transition', 'Are you eating more plant-based?', 1.25, 2, true),
  ('Meat Consumption Reduction', 'Have you reduced meat consumption?', 1.30, 2, true),
  ('Food Miles Awareness', 'Do you consider food miles?', 1.20, 2, true),
  ('Zero Waste Lifestyle', 'Are you pursuing zero waste?', 1.35, 2, true),
  ('Secondhand Clothing Shopping', 'Do you buy secondhand clothes?', 1.25, 2, true),
  ('Clothing Donation Habits', 'Do you donate clothes regularly?', 1.20, 2, true),
  ('Fast Fashion Opinions', 'What do you think of fast fashion?', 1.30, 2, true),
  ('Sustainable Fashion Interest', 'Are you interested in sustainable fashion?', 1.35, 2, true),
  ('Capsule Wardrobe Concept', 'Do you have a capsule wardrobe?', 1.25, 2, true),
  ('Clothing Repair vs Replace', 'Do you repair clothes?', 1.20, 2, true),
  ('Laundry Frequency', 'How often do you do laundry?', 1.15, 2, true),
  ('Laundry Product Preferences', 'What laundry products do you use?', 1.20, 2, true),
  ('Dry Cleaning Usage', 'Do you use dry cleaning?', 1.20, 2, true),
  ('Ironing Habits', 'Do you iron your clothes?', 1.10, 2, true),
  ('Shoe Collection Size', 'How many pairs of shoes do you own?', 1.15, 2, true),
  ('Shoe Comfort vs Style', 'Comfort or style in shoes?', 1.20, 2, true),
  ('Athletic Shoe Preferences', 'What athletic shoes do you prefer?', 1.25, 2, true),
  ('Fashion Trend Following', 'Do you follow fashion trends?', 1.20, 2, true),
  ('Personal Style Evolution', 'How has your style changed?', 1.25, 2, true),
  ('Accessory Usage', 'What accessories do you wear?', 1.15, 2, true),
  ('Jewelry Preferences', 'Do you wear jewelry?', 1.20, 2, true),
  ('Watch Ownership', 'Do you wear a watch?', 1.15, 2, true),
  ('Sunglasses Usage', 'Do you wear sunglasses?', 1.15, 2, true),
  ('Hat and Cap Wearing', 'Do you wear hats?', 1.10, 2, true),
  ('Scarf and Winter Accessories', 'Do you use winter accessories?', 1.15, 2, true),
  ('Bag and Purse Preferences', 'What type of bag do you carry?', 1.20, 2, true),
  ('Wallet Type Preference', 'What wallet do you use?', 1.15, 2, true),
  ('Fragrance and Perfume Usage', 'Do you wear fragrance?', 1.20, 2, true),
  ('Makeup Usage Frequency', 'How often do you wear makeup?', 1.20, 2, true),
  ('Skincare Routine Complexity', 'How complex is your skincare?', 1.25, 2, true),
  ('Sun Protection Habits', 'Do you use sunscreen?', 1.25, 2, true),
  ('Hair Care Routine', 'Tell us about your hair care', 1.20, 2, true),
  ('Hair Styling Frequency', 'How often do you style hair?', 1.15, 2, true),
  ('Salon Visit Frequency', 'How often do you visit salons?', 1.20, 2, true),
  ('At-Home Hair Color', 'Do you color hair at home?', 1.20, 2, true),
  ('Nail Care Habits', 'Do you get manicures?', 1.20, 2, true),
  ('Facial Treatment Interest', 'Are you interested in facials?', 1.25, 2, true),
  ('Massage Frequency', 'How often do you get massages?', 1.25, 2, true),
  ('Spa Treatment Preferences', 'What spa treatments do you like?', 1.30, 2, true),
  ('Self-Care Budget', 'How much do you spend on self-care?', 1.25, 2, true),
  ('Beauty Product Preferences', 'Natural or conventional beauty products?', 1.25, 2, true),
  ('Bathroom Organization', 'How do you organize bathroom products?', 1.15, 2, true),
  ('Morning Grooming Time', 'How long is your morning routine?', 1.15, 2, true),
  ('Grooming Product Loyalty', 'Are you loyal to grooming brands?', 1.20, 2, true),
  ('Sample Product Trying', 'Do you try product samples?', 1.15, 2, true),
  ('Beauty Influencer Following', 'Do you follow beauty influencers?', 1.20, 2, true),
  ('Makeup Tutorial Watching', 'Do you watch makeup tutorials?', 1.20, 2, true),
  ('Beard Care Routine', 'Do you have a beard care routine?', 1.20, 2, true),
  ('Shaving Preferences', 'Electric or manual shaving?', 1.15, 2, true),
  ('Dental Care Products', 'What dental products do you use?', 1.20, 2, true),
  ('Teeth Whitening Interest', 'Have you whitened your teeth?', 1.25, 2, true),
  ('Orthodontic Treatment', 'Have you had braces?', 1.20, 2, true),
  ('Vision Correction', 'Do you wear glasses or contacts?', 1.20, 2, true),
  ('Eye Care Routine', 'How do you care for your eyes?', 1.20, 2, true),
  ('Hearing Protection', 'Do you protect your hearing?', 1.20, 2, true),
  ('Posture Awareness', 'Are you aware of your posture?', 1.20, 2, true),
  ('Ergonomic Setup', 'Do you have an ergonomic workspace?', 1.25, 2, true),
  ('Standing Desk Usage', 'Do you use a standing desk?', 1.25, 2, true),
  ('Office Chair Comfort', 'How comfortable is your chair?', 1.20, 2, true),
  ('Desk Organization', 'How organized is your desk?', 1.15, 2, true),
  ('Workspace Personalization', 'Do you personalize your workspace?', 1.20, 2, true),
  ('Natural Light Availability', 'Do you have natural light at work?', 1.20, 2, true),
  ('Indoor Plant Ownership', 'Do you have indoor plants?', 1.20, 2, true),
  ('Air Quality Concerns', 'Are you concerned about air quality?', 1.25, 2, true),
  ('Air Purifier Usage', 'Do you use an air purifier?', 1.25, 2, true),
  ('Humidifier/Dehumidifier', 'Do you control humidity?', 1.20, 2, true),
  ('Temperature Preference', 'What temperature do you prefer?', 1.15, 2, true),
  ('Heating/Cooling Preferences', 'How do you heat and cool your home?', 1.25, 2, true),
  ('Ceiling Fan Usage', 'Do you use ceiling fans?', 1.15, 2, true),
  ('Window Treatment Preferences', 'What window treatments do you have?', 1.20, 2, true),
  ('Flooring Preferences', 'What flooring do you prefer?', 1.25, 2, true),
  ('Carpet vs Hardwood', 'Carpet or hardwood floors?', 1.20, 2, true),
  ('Rug Usage', 'Do you use area rugs?', 1.15, 2, true),
  ('Wall Color Preferences', 'What wall colors do you like?', 1.20, 2, true),
  ('Wallpaper Usage', 'Do you use wallpaper?', 1.20, 2, true),
  ('Artwork Display', 'Do you display art in your home?', 1.25, 2, true),
  ('Photo Display Habits', 'Do you display family photos?', 1.15, 2, true),
  ('Shelf and Storage Organization', 'How do you organize storage?', 1.20, 2, true),
  ('Closet Organization', 'How organized is your closet?', 1.20, 2, true),
  ('Storage Solution Preferences', 'What storage solutions do you use?', 1.25, 2, true),
  ('Garage Organization', 'How organized is your garage?', 1.20, 2, true),
  ('Basement Usage', 'What do you use your basement for?', 1.20, 2, true),
  ('Attic Storage', 'Do you store items in the attic?', 1.15, 2, true),
  ('Shed Ownership', 'Do you have a storage shed?', 1.15, 2, true),
  ('Tool Collection', 'What tools do you own?', 1.20, 2, true),
  ('DIY Skill Level', 'How skilled are you at DIY?', 1.25, 2, true),
  ('Home Repair Confidence', 'Can you do home repairs?', 1.25, 2, true),
  ('Contractor Hiring Experience', 'Have you hired contractors?', 1.30, 2, true),
  ('Home Warranty Ownership', 'Do you have a home warranty?', 1.25, 2, true),
  ('Property Tax Burden', 'How do you feel about property taxes?', 1.30, 2, true),
  ('HOA Membership', 'Are you in an HOA?', 1.25, 2, true),
  ('Condo vs House Preference', 'Condo or house preference?', 1.25, 2, true),
  ('Urban vs Suburban Living', 'Urban or suburban preference?', 1.25, 2, true),
  ('Rural Living Interest', 'Interested in rural living?', 1.30, 2, true),
  ('Dream Home Description', 'Describe your dream home', 1.30, 2, true),
  ('Tiny House Interest', 'Interested in tiny houses?', 1.25, 2, true),
  ('Minimalist Home Aesthetic', 'Do you prefer minimalist design?', 1.25, 2, true),
  ('Maximalist Decorating', 'Do you like lots of decor?', 1.20, 2, true),
  ('Vintage vs Modern Style', 'Vintage or modern style?', 1.20, 2, true),
  ('Rustic Decor Interest', 'Do you like rustic decor?', 1.20, 2, true),
  ('Industrial Design Appeal', 'Do you like industrial design?', 1.25, 2, true),
  ('Coastal/Beach Theme', 'Do you like coastal decor?', 1.20, 2, true),
  ('Bohemian Style Interest', 'Are you into boho style?', 1.20, 2, true),
  ('Scandinavian Design', 'Do you like Scandinavian design?', 1.25, 2, true),
  ('Mid-Century Modern', 'Interested in mid-century modern?', 1.25, 2, true),
  ('Traditional Home Style', 'Do you prefer traditional style?', 1.20, 2, true),
  ('Contemporary Design', 'Do you like contemporary design?', 1.25, 2, true),
  ('Eclectic Mixing', 'Do you mix design styles?', 1.20, 2, true),
  ('Color Scheme Preferences', 'What color schemes do you like?', 1.20, 2, true),
  ('Neutral Color Love', 'Do you prefer neutral colors?', 1.15, 2, true),
  ('Bold Color Usage', 'Do you use bold colors?', 1.20, 2, true),
  ('Accent Wall Popularity', 'Do you have accent walls?', 1.20, 2, true),
  ('Open Concept Preference', 'Do you like open floor plans?', 1.25, 2, true),
  ('Kitchen Island Importance', 'How important is a kitchen island?', 1.25, 2, true),
  ('Kitchen Appliance Preferences', 'What kitchen appliances matter most?', 1.30, 2, true),
  ('Cooking Space Needs', 'How much cooking space do you need?', 1.20, 2, true),
  ('Pantry Organization', 'How do you organize your pantry?', 1.20, 2, true),
  ('Refrigerator Organization', 'How do you organize your fridge?', 1.15, 2, true),
  ('Meal Prep Habits', 'Do you meal prep?', 1.25, 2, true),
  ('Freezer Usage Patterns', 'How do you use your freezer?', 1.15, 2, true),
  ('Kitchen Gadget Collection', 'What kitchen gadgets do you have?', 1.20, 2, true),
  ('Specialty Appliance Ownership', 'Do you have specialty appliances?', 1.25, 2, true),
  ('Coffee Maker Type', 'What type of coffee maker do you have?', 1.20, 2, true),
  ('Blender Usage', 'Do you use a blender?', 1.15, 2, true),
  ('Food Processor Ownership', 'Do you have a food processor?', 1.20, 2, true),
  ('Stand Mixer Usage', 'Do you use a stand mixer?', 1.20, 2, true),
  ('Slow Cooker Preferences', 'Do you use a slow cooker?', 1.20, 2, true),
  ('Instant Pot Experience', 'Do you have an Instant Pot?', 1.25, 2, true),
  ('Air Fryer Usage', 'Do you use an air fryer?', 1.25, 2, true),
  ('Toaster Oven vs Regular Toaster', 'Toaster oven or regular toaster?', 1.15, 2, true),
  ('Microwave Usage Frequency', 'How often do you use a microwave?', 1.15, 2, true),
  ('Dishwasher vs Hand Washing', 'Dishwasher or hand wash?', 1.15, 2, true),
  ('Kitchen Cleaning Frequency', 'How often do you clean the kitchen?', 1.15, 2, true),
  ('Cleaning Product Preferences', 'Natural or conventional cleaners?', 1.20, 2, true),
  ('Cleaning Service Usage', 'Do you use a cleaning service?', 1.25, 2, true),
  ('Cleaning Schedule', 'Do you have a cleaning schedule?', 1.15, 2, true),
  ('Laundry Room Organization', 'How is your laundry room organized?', 1.20, 2, true),
  ('Washer and Dryer Preferences', 'Top load or front load?', 1.25, 2, true),
  ('Bathroom Cleaning Routine', 'How do you clean bathrooms?', 1.15, 2, true),
  ('Bathroom Storage Solutions', 'How do you store bathroom items?', 1.20, 2, true),
  ('Shower vs Bath Preference', 'Shower or bath preference?', 1.15, 2, true),
  ('Bathtub Usage Frequency', 'How often do you take baths?', 1.15, 2, true),
  ('Bathroom Renovation Interest', 'Want to renovate your bathroom?', 1.30, 2, true),
  ('Kitchen Renovation Plans', 'Want to renovate your kitchen?', 1.35, 2, true),
  ('Home Addition Considerations', 'Considering a home addition?', 1.35, 2, true),
  ('Basement Finishing Plans', 'Want to finish your basement?', 1.30, 2, true),
  ('Outdoor Living Space', 'Do you have outdoor living space?', 1.25, 2, true),
  ('Deck or Patio Preference', 'Deck or patio preference?', 1.25, 2, true),
  ('Outdoor Kitchen Interest', 'Want an outdoor kitchen?', 1.35, 2, true),
  ('Swimming Pool Ownership', 'Do you have a pool?', 1.30, 2, true),
  ('Hot Tub Experience', 'Do you have a hot tub?', 1.30, 2, true),
  ('Fire Pit Usage', 'Do you have a fire pit?', 1.25, 2, true),
  ('Outdoor Furniture Quality', 'How is your outdoor furniture?', 1.25, 2, true),
  ('Patio Umbrella Usage', 'Do you have patio umbrellas?', 1.15, 2, true),
  ('Outdoor Lighting', 'What outdoor lighting do you have?', 1.25, 2, true),
  ('Landscape Lighting Interest', 'Want landscape lighting?', 1.30, 2, true),
  ('Landscaping Maintenance', 'Do you maintain landscaping?', 1.25, 2, true),
  ('Lawn Care Routine', 'How do you care for your lawn?', 1.20, 2, true),
  ('Lawn Service Usage', 'Do you use a lawn service?', 1.25, 2, true),
  ('Gardening Skill Level', 'How skilled are you at gardening?', 1.20, 2, true),
  ('Vegetable Garden Ownership', 'Do you have a vegetable garden?', 1.25, 2, true),
  ('Flower Garden Maintenance', 'Do you grow flowers?', 1.20, 2, true),
  ('Container Gardening', 'Do you do container gardening?', 1.20, 2, true),
  ('Herb Garden Interest', 'Do you grow herbs?', 1.25, 2, true),
  ('Fruit Tree Ownership', 'Do you have fruit trees?', 1.25, 2, true),
  ('Composting for Garden', 'Do you compost for gardening?', 1.25, 2, true),
  ('Organic Gardening Practices', 'Do you garden organically?', 1.30, 2, true),
  ('Garden Tool Collection', 'What garden tools do you have?', 1.20, 2, true),
  ('Lawn Mower Type', 'What type of lawn mower do you have?', 1.20, 2, true),
  ('Leaf Blower Usage', 'Do you use a leaf blower?', 1.15, 2, true),
  ('Snow Removal Methods', 'How do you remove snow?', 1.20, 2, true),
  ('Seasonal Decoration Enthusiasm', 'Do you decorate for seasons?', 1.20, 2, true),
  ('Holiday Decoration Budget', 'How much do you spend on decorations?', 1.25, 2, true),
  ('Christmas Tree Preference', 'Real or artificial tree?', 1.15, 2, true),
  ('Holiday Lighting Display', 'Do you put up holiday lights?', 1.20, 2, true),
  ('Halloween Decoration Level', 'How much do you decorate for Halloween?', 1.20, 2, true),
  ('Thanksgiving Hosting', 'Do you host Thanksgiving?', 1.25, 2, true),
  ('Holiday Cooking Responsibilities', 'Do you cook for holidays?', 1.20, 2, true),
  ('Gift Giving Philosophy', 'What is your gift giving approach?', 1.25, 2, true),
  ('Gift Wrapping Skills', 'How good are you at wrapping?', 1.15, 2, true),
  ('Birthday Celebration Preferences', 'How do you celebrate birthdays?', 1.20, 2, true),
  ('Party Hosting Frequency', 'How often do you host parties?', 1.25, 2, true),
  ('Event Planning Skills', 'How good are you at planning events?', 1.25, 2, true),
  ('Potluck Participation', 'Do you like potlucks?', 1.15, 2, true),
  ('Dinner Party Hosting', 'Do you host dinner parties?', 1.25, 2, true),
  ('Game Night Participation', 'Do you have game nights?', 1.20, 2, true),
  ('Movie Night Habits', 'Do you have movie nights?', 1.20, 2, true),
  ('Binge Watching Preferences', 'What do you binge watch?', 1.20, 2, true),
  ('TV Show Genre Preferences', 'What TV genres do you like?', 1.20, 2, true),
  ('Movie Genre Preferences', 'What movie genres do you prefer?', 1.20, 2, true),
  ('Favorite Streaming Service', 'Which streaming service is your favorite?', 1.25, 2, true)
on conflict do nothing;
